#include <ncurses.h>
#include <stdlib.h>
#include <time.h>

void arraysel(int *array) {

  int sortedarray[18] = {1,  2,  3,  4,  5,  6,  7,  8,  9,
                         10, 11, 12, 13, 14, 15, 16, 17, 18};
  int defaultarray[18] = {1,  18, 2,  17, 3,  16, 4,  15, 5,
                          14, 6,  13, 7,  12, 8,  11, 9,  10};

  // Generated by https://random.org/sequences
  int randomarray1[18] = {8,  11, 4,  17, 9,  14, 16, 7, 1,
                          13, 12, 18, 2,  10, 3,  5,  15};
  int randomarray2[18] = {7,  18, 17, 4,  5,  10, 8, 3, 6,
                          11, 13, 12, 15, 16, 1,  9, 2, 14};

  int mX, mY;
  getmaxyx(stdscr, mY, mX);

  WINDOW *main = newwin(34, 92, (mY - 34) / 2, (mX - 92) / 2);
  init_pair(1, COLOR_CYAN, COLOR_CYAN);
  init_pair(2, COLOR_BLACK, COLOR_WHITE);

  box(main, 0, 0);
  wbkgd(stdscr, COLOR_PAIR(1));
  wbkgd(main, COLOR_PAIR(2));
  wattron(main, COLOR_PAIR(2));
  keypad(main, true);

  // Printing
  mvwprintw(main, 2, 36, "Array Customisation");
  wattron(main, A_BOLD);
  mvwprintw(main, 7, 1, "Chosen Array:");
  mvwprintw(main, 30, 1, "Controls:");
  mvwprintw(main, 31, 1,
            "LEFT: Selection Lower  RIGHT: Selection Raise  ENTER: Confirm "
            "Selection");
  mvwprintw(main, 32, 1,
            "'D': Use default array  'R': Use quasi-random array.");

  int arrayposition = 0;
  int choice = 0;
  int highlight = 0;
  keypad(main, true);

  refresh();
  wrefresh(main);
  wrefresh(stdscr);

  do {

    for (int i = 0; i < 18; i++) {
      if (i == highlight)
        wattron(main, A_REVERSE);

      mvwprintw(main, 5, 6 + (i * 3), "%d", sortedarray[i]);

      wattroff(main, A_REVERSE);
      wattron(main, COLOR_PAIR(2));
      wrefresh(main);
    }

    wrefresh(stdscr);

    choice = wgetch(main);
    switch (choice) {

    case KEY_LEFT:
      if (highlight == 0)
        break;
      highlight--;
      break;

    case KEY_RIGHT:
      if (highlight == 17)
        break;
      highlight++;
      break;

    case 'd':
      arrayposition = 18;
      for (int i = 0; i < 18; i++)
        array[i] = defaultarray[i];
      break;

    case 'r':
      arrayposition = 18;
      srand(time(0));
      int randomoffset = rand() % 18;
      int arrayselector = rand() % 2;
      for (int i = 0; i < 18; i++) {

        // This corrects the oppertunity for data... overflow(?) to arise.
        if (randomoffset > 17)
          randomoffset = 0;

        switch (arrayselector) {

        case 0:
          array[i] = randomarray1[randomoffset];
          break;

        case 1:
          array[i] = randomarray2[randomoffset];
          break;

        default:
          break;
        }

        randomoffset++;
      }

    case 10:
      array[arrayposition] = sortedarray[highlight];
      mvwprintw(main, 8, 1 + 3 * arrayposition, "%d", array[arrayposition]);
      arrayposition++;
      break;

    default:
      break;
    }

  } while (arrayposition < 18);

  return;
}
