#include <ncurses.h>
#include <stdlib.h>
#include <time.h>

void arraysel(int *array) {

    int defaultarray[18] = {1,  18, 2,  17, 3,  16, 4,  15, 5,
                            14, 6,  13, 7,  12, 8,  11, 9,  10
                           };

    // Generated by https://random.org/sequences
    int randomarray[18] = {8,  11, 4,  17, 9,  14, 16, 7,  1,
                           13, 12, 18, 2,  10, 3,  5,  15, 6
                          };

    int mX, mY;
    getmaxyx(stdscr, mY, mX);

    WINDOW *main = newwin(34, 92, (mY - 34) / 2, (mX - 92) / 2);
    init_pair(1, COLOR_CYAN, COLOR_CYAN);
    init_pair(2, COLOR_BLACK, COLOR_WHITE);
    init_pair(3, COLOR_RED, COLOR_WHITE);

    box(main, 0, 0);
    wbkgd(stdscr, COLOR_PAIR(1));
    wbkgd(main, COLOR_PAIR(2));
    wattron(main, COLOR_PAIR(2));
    keypad(main, true);

    // Printing
    mvwprintw(main, 2, 36, "Array Customisation");

    wattron(main, A_BOLD);
    mvwprintw(main, 27, 1, "Controls:");
    mvwprintw(main, 28, 1,
              "'d' = Use the default array. 'r' = Use a randomised array.");
    mvwprintw(main, 29, 1, "RETURN = Enter Custom-Entry Mode");
    mvwprintw(main, 31, 1, "When in custom-entry mode:");
    mvwprintw(main, 32, 1, "KEYS 0 - 9: Enter Entry  ENTER: Confirm Selection");

    int arrayposition = 0;
    int initialselection = 0;
    keypad(main, true);

    refresh();
    wrefresh(main);
    wrefresh(stdscr);

    initialselection = wgetch(main);
    switch (initialselection) { // This is what determines which "mode" the
    // program goes into.

    case 'd': // The user has chosen to go with the default array.
        for (int i = 0; i < 18; i++)
            array[i] = defaultarray[i];
        return;

    case 'r': // The user has chosen to go with a semi-random array.
        srand(time(0));
        arrayposition = rand() % 18;
        for (int i = 0; i < 18; i++) {
            if (arrayposition == 18) // If we reached the 'end' of the array's random
                // offset, that being 18...
                arrayposition = 0;     // Then it's simply set back to 0.

            array[i] = randomarray[arrayposition];
            arrayposition++;
        }
        return;

    case 10: // The user has chosen to enter custom-entry mode.
        break;
    }

    // Input-Output Routine
    int redundancycheck =
        0;           // This is used to check if an entry has already been used.
    int customentry; // This is called seperately for the sake of checking for
    // redundancy.

    // This is for aesthetic purposes.
    mvwprintw(main, 11, 1, "Current array:");
    for (int i = 0; i < 18; i++)
        mvwprintw(main, 12, 1 + (3 * i), "%d", array[i]);

    echo();
    do {

        wattron(main, A_BOLD);
        mvwprintw(main, 6, 1, "You are now in custom entry mode.        ");
        mvwprintw(main, 7, 1,
                  "Please enter a sequence consisting of numbers 1 through 18, "
                  "inclusive,");
        mvwprintw(main, 8, 1, "without repetition.");
        wrefresh(main);

        while (1) {

            mvwscanw(main, 5, 1, "%d", &customentry);

            // This checks for redundancy.
            for (int i = 0; i < 18; i++) {
                if (customentry == array[i])
                    redundancycheck++;
            }

            // If the number is valid, then break and copy it to the array.
            if (customentry > 0 && customentry < 19 && redundancycheck == 0)
                break;

            // This routine only plays out if the user entered an invalid number.
            wattron(main, COLOR_PAIR(3));

            if (redundancycheck != 0)
                mvwprintw(main, 6, 1, "ERROR! Entry has already been entered!");
            else
                mvwprintw(main, 6, 1, "ERROR! You entered an invalid entry!");

            // This simply clears the space that an entry is entered into.
            mvwprintw(main, 5, 1, "    ");

            wrefresh(main);
            wattron(main, COLOR_PAIR(2));

            // For the sake of safety, the redundancy check is reset.
            redundancycheck = 0;
        }

        // Same function as within the previous while(1) loop.
        mvwprintw(main, 5, 1, "    ");

        // The custom entry has been verified to be a valid entry, so we add it to
        // the array.
        array[arrayposition] = customentry;

        // Then we reprint the values of the array.
        wattroff(main, A_BOLD);
        mvwprintw(main, 11, 1, "Current array:");
        for (int i = 0; i < 18; i++)
            mvwprintw(main, 12, 1 + (3 * i), "%d", array[i]);

        // We wrap up by adding one to the array position.
        arrayposition++;

    } while (array[17] == 0);

    return;
}
